version: 3

project:
  locator: custom+43030/marissa-fossa-type-license-test
  id: github.com/cmboling/marissa-fossa-type-license-test
  name: marissa-fossa-type-license-test
  labels:
    - cmboling-test
