version: 3

server: https://app.fossa.com
apiKey: a1b2c3

project:
  locator: custom+1/github.com/fossas/fossa-cli
  id: github.com/fossas/fossa-cli
  name: fossa-cli
  team: cli-team
  teams: 
    - cli-team-1
    - cli-team-2
  policy: custom-cli-policy
  link: fossa.com
  url: github.com/fossas/fossa-cli
  jiraProjectKey: jira-key
  releaseGroup:
    name: release-group-name
    release: 123-release-candidate
  labels:
    - project-label-1
    - test-project

releaseGroup:
  title: release-group-title
  release: release-group-release
  releaseGroupProjects:
    - projectLocator: custom+123/git@github.com/fossas/fossa-cli
      projectRevision: "12345"
      projectBranch: master 
    - projectLocator: custom+123/git@github.com/example
      projectRevision: "67890"
      projectBranch: master
  licensePolicy: license-policy-name
  securityPolicy: security-policy-name
  qualityPolicy: quality-policy-name
  teams:
    - team1
    - team2


revision:
  commit: "12345"
  branch: master

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    only:
      - "**/*.rb"
    exclude:
      - ".git/**"
      - "test/**/*.rb"

targets:
  only:
    - type: maven
      path: foo/bar
  exclude:
    - type: bundler

paths:
  only:
    - ./vendor/django
    - ./test
  exclude:
    - ./vendor/django/test

telemetry:
  scope: full

customLicenseSearch:
  - matchCriteria: "[Pp]roprietary [Ll]icense"
    name: "Proprietary License"

experimentalKeywordSearch:
  - matchCriteria: "[Pp]roprietary and [Cc]onfidential"
    name: "Proprietary and Confidential match"
